ALTER TABLE users
ADD COLUMN IF NOT EXISTS phone TEXT NULL,
ADD COLUMN IF NOT EXISTS middle_name TEXT NULL;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS description TEXT NULL,
ADD COLUMN IF NOT EXISTS discount_price NUMERIC(12, 2) NULL;
